name: unit-tests

on:
  pull_request:
    types:
      - opened
      - labeled
      - reopened
      - synchronize

jobs:
  unit-tests:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip_ci') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.7.0
          cache: 'npm'

      - name: Npm install
        run: npm install

      - name: Run test
        run: npm run test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-results.xml
